### ISSUE TITLE
Typing is not hidden whilst in dms

### ISSUE THREAD

**Issue by xcruxiex** [Drylotrans/better-invisible#1]
Whilst typing in dms, it does not hide to the other user (if it matters, they're on mobile).

**Comment by Drylotrans** [comment]
A Discord update broke the way typing was removed when in invisible mode, I made a new way to do it ([here](https://github.com/Drylotrans/better-invisible/commit/08dc8848801dc1faf0b36843e51a31986c8b48f7)) but in case you have a better way, do a pull request

Thanks for you advice
